name: Deploy to AWS Elastic Beanstalk
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  deploy:
    name: Deploy to Elastic Beanstalk
    environment: Elastic Beanstalk
    runs-on: ubuntu-latest
    steps:
      - name: Check-out commit
        uses: actions/checkout@v2
      - name: Write .env file
        run: >
          ./generate-foundry-env.sh
          -k ${{ secrets.FOUNDRY_ADMIN_KEY }}
          -p ${{ secrets.FOUNDRY_PASSWORD }}
          -t ${{ secrets.FOUNDRY_TIMEZONE }}
          -u ${{ secrets.FOUNDRY_USERNAME }}
      - name: Validate docker-compose.yml
        run: docker-compose config --quiet
      - name: Generate deployment.zip
        run: zip -r deployment.zip . -x .github/ '*.git*' '*.idea*' '*.DS_Store*' '**.md'
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ap-southeast-2
          application_name: foundryvtt
          environment_name: Foundryvtt-env
          version_label: "Commit ${{ github.SHA }}"
          version_description: "GitHub Actions run #${{ github.RUN_NUMBER }}"
          deployment_package: deployment.zip
          wait_for_deployment: true
