name: Deploy to AWS Elastic Beanstalk
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  deploy:
    name: Deploy to Elastic Beanstalk
    environment: Elastic Beanstalk
    runs-on: ubuntu-latest
    steps:
      - name: Check-out commit
        uses: actions/checkout@v2
      - name: Install EB CLI
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli --upgrade
          eb --version
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Initialize EB CLI
        run: eb init foundryvtt --platform docker --region ap-southeast-2
      - name: Set EB environment
        run: (eb use Foundryvtt-env && eb status Foundryvtt-env) # || eb create Foundryvtt-env
      - name: Set environment variables
        run: eb setenv FOUNDRY_USERNAME=${{ secrets.FOUNDRY_USERNAME }} FOUNDRY_PASSWORD=${{ secrets.FOUNDRY_PASSWORD }} FOUNDRY_ADMIN_KEY=${{ secrets.FOUNDRY_ADMIN_KEY }} TIMEZONE=${{ secrets.FOUNDRY_TIMEZONE }}
      - name: Deploy
        run: eb deploy Foundryvtt-env --label "Commit ${{ github.SHA }}" --message "GitHub Actions run \#${{ github.RUN_NUMBER }}"
