name: Deploy to AWS Elastic Beanstalk
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  deploy:
    name: Deploy to Elastic Beanstalk
    runs-on: ubuntu-latest
    steps:
      - name: Check-out commit
        uses: actions/checkout@v2
      - name: Validate docker-compose.yml
        run: docker-compose config --quiet
      - name: Generate deployment.zip
        run: zip -r deployment.zip docker-compose.yml  # zip is unnecessary if only deploying a docker-compose.yml file to EB
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ap-southeast-2
          application_name: foundryvtt
          environment_name: Foundryvtt-env
          version_label: "Commit ${{ github.SHA }}"
          version_description: "GitHub Actions run #${{ github.RUN_NUMBER }}"
          deployment_package: deployment.zip
          wait_for_deployment: true
